export let checkbox={
	id:'',
	compIcon:'checkbox',
	compName:'复选框',
	ele:'el-checkbox-group',
	title:'复选框',
	showLabel:true,
	required:false,
	disabled:false,
	size:'medium',
	min:0,
	max:5,
	'text-color':"#ffffff",
	fill:"#409EFF",
	childIndex:0,
	value:[],
	child:[{label:'选项一'},{label:'选项二'}],
	childAttr:{
		border:false
	}
}